version: '3.8'

services:
  web:
    build: .
    command: bundle exec rails server -b 0.0.0.0
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:password@db:5432/myapp
      DATABASE_USER: postgres
      DATABASE_PASSWORD: password

  db:
    image: postgres:13
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: myapp

  redis:
    image: "redis:7-alpine"
    ports:
      - 6379
    volumes:
      - ./tmp/redis_data:/var/lib/redis/data

volumes:
  pgdata:
